DROP TABLE SAMPLE_T;

CREATE TABLE SAMPLE_T (
        ID NUMBER PRIMARY KEY --제약조건 NOT NULL 중복불가!!
      , NAME VARCHAR(30) NOT NULL
      , GENDER CHAR(1) CHECK(GENDER IN ('F','M'))
      , AGE NUMBER DEFAULT(0) NOT NULL
);

INSERT INTO SAMPLE_T VALUES(SEQ_TEST.NEXTVAL,'홍길동', 'M',32);       
INSERT INTO SAMPLE_T VALUES(SEQ_TEST.NEXTVAL,'김수정', 'F',28); 
INSERT INTO SAMPLE_T VALUES(SEQ_TEST.NEXTVAL,'박정길', 'M',36);
INSERT INTO SAMPLE_T VALUES(SEQ_TEST.NEXTVAL,'박정길', 'M',36);
INSERT INTO SAMPLE_T VALUES(SEQ_TEST.NEXTVAL,'박정길', 'M',36);


SELECT *FROM SAMPLE_T;

CREATE OR REPLACE VIEW V_SAMPLE_T
      AS SELECT  ID
               , NAME
               , GENDER
               , AGE  --가상열에 대해서는 추가작업을 할 수 없음
            FROM SAMPLE_T
         -- WHERE AGE BETWEEN 30 AND 35
WITH READ ONLY;
--WITH CHECK OPTION;



SELECT * FROM V_SAMPLE_T;

SELECT * FROM USER_VIEWS;

INSERT INTO V_SAMPLE_T VALUES(5, '이기석','M',20);

UPDATE V_SAMPLE_T
    SET AGE = AGE + 1;--VIEW 테이블에서는 보는것만 가능

DELETE FROM V_SAMPLE_T;--행을 지울때 쓰는 것 drop은 테이블전테 삭제하는것
ROLLBACK;
    