-- 직원 테이블
SELECT * 
  FROM EMPLOYEES;
 
 SELECT EMPLOYEE_ID
       , FIRST_NAME
       , LAST_NAME
   FROM EMPLOYEES;

  SELECT  EMPLOYEE_ID
        , FIRST_NAME
        , LAST_NAME
   FROM EMPLOYEES
   WHERE EMPLOYEE_ID >= 200;
  
  
  SELECT  EMPLOYEE_ID
        , FIRST_NAME
        , LAST_NAME
   FROM EMPLOYEES
   WHERE EMPLOYEE_ID >= 200
      OR FIRST_NAME = 'Steven';
     
     
  SELECT EMPLOYEE_ID AS "사번"
       , FIRST_NAME AS 이름
       , LAST_NAME 성
       , EMAIL "이메일 주소"
    FROM EMPLOYEES;  
  
   
  SELECT EMPLOYEE_ID AS "사번"--마지막3해석
        ,FIRST_NAME AS "이름"
        ,LAST_NAME AS "성"
     FROM EMPLOYEES--제일먼저1
    WHERE EMPLOYEE_ID >= 200;--그다음해석2 --"사번"별칭 만들어서 넣는것 안됨
    
  SELECT FIRST_NAME || ' ' || LAST_NAME AS "이름"  
        ,SALARY * 12 AS "연봉"
      FROM EMPLOYEES;
     
 -- 조건절에서 사용하는 연산자
 -- AND, OR , NOT, IN, NOT IN ,BETWEEN ... AND
 -- LIKE, NOT LIKE, IS NULL , IS NOT NULL  
  SELECT *
     FROM EMPLOYEES 
    WHERE NOT EMPLOYEE_ID >= 200;
   
  SELECT *
     FROM EMPLOYEES 
    WHERE EMPLOYEE_ID  IN(200, 201, 202, 203);
   
  SELECT *
     FROM EMPLOYEES 
    WHERE EMPLOYEE_ID NOT IN(200, 201, 202, 203);
   
   SELECT *
    FROM EMPLOYEES
   WHERE EMPLOYEE_ID BETWEEN 200 AND 203;   
  
  
  SELECT *
     FROM EMPLOYEES 
    WHERE FIRST_NAME LIKE 'S%';
   
  SELECT *
     FROM EMPLOYEES 
    WHERE FIRST_NAME LIKE '%ea%';
   
  SELECT *
     FROM EMPLOYEES 
    WHERE FIRST_NAME LIKE '_____';
   
  SELECT *
     FROM EMPLOYEES 
    WHERE FIRST_NAME LIKE 'D____';--언더바 하나가 문자 하나다.
   
  SELECT *
     FROM EMPLOYEES 
    WHERE JOB_ID  LIKE '%&____' ESCAPE '&';--이스케이프 문자
  SELECT *
     FROM EMPLOYEES 
    WHERE JOB_ID  LIKE '%&_____' ESCAPE '&';--이스케이프 문자
    
  SELECT *
     FROM EMPLOYEES 
    WHERE JOB_ID  NOT LIKE '%&____' ESCAPE '&';--이스케이프 문자
   
  SELECT *
   FROM EMPLOYEES
  WHERE COMMISSION_PCT IS NULL;
 
  SELECT *
   FROM EMPLOYEES
  WHERE COMMISSION_PCT IS NOT NULL;
 
 SELECT *
  FROM EMPLOYEES
   WHERE NOT EMPLOYEE_ID >=200
     OR EMPLOYEE_ID = 100;  
 
 SELECT *
  FROM EMPLOYEES
   WHERE NOT (EMPLOYEE_ID >=200
     OR EMPLOYEE_ID = 100);  
  
  
  
  
-- 부서 테이블
SELECT * FROM  DEPARTMENTS;

-- 직급 테이블
SELECT * FROM JOBS;

-- 국가 테이블
SELECT * FROM COUNTRIES;

-- 국가별 지역 테이블
SELECT * FROM LOCATIONS;

-- 대륙 테이블
SELECT * FROM REGIONS;






