--렌터카 저장 정보 테이블 만들기
CREATE TABLE RENT_CAR(
     CARNUMBER  VARCHAR(10)    PRIMARY KEY
    ,CARNAME    VARCHAR2(20)
    ,CARCOLOR   VARCHAR2(20)
    ,CARSIZE    NUMBER(5)
    ,CARMARKET   VARCHAR2(20)
);
DESC RENT_CAR;

SELECT * FROM RENT_CAR;