CREATE OR REPLACE FUNCTION FUNC_TEST1(V1 NUMBER) RETURN NUMBER
IS                          -- 함수명      매개변수        반환타입
BEGIN
	 RETURN V1+10;
END;


SELECT FUNC_TEST1(5) FROM DUAL;

CREATE OR REPLACE FUNCTION FUNC_TEST3(v1 NUMBER, v2 NUMBER) RETURN VARCHAR2
IS
    var VARCHAR2(10) := ' Done';
BEGIN
	 RETURN v1+v2 || var;
END;

SELECT FUNC_TEST3(10,20) FROM DUAL;
